name: Echo Repository Name

on:
  repository_dispatch:
    types: [custom_event]

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo repository name
      run: |
           echo "Hello, this is the repository: ${{ github.repository }}"